---
# Docker pre-configuration for CentOS

- name: Add Docker Community Edition repository
  become: true
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

# Docker package name is 'docker-ce'

