---
# Perform Rocky-specific tasks

# Use the centos repo for Docker
- name: Add Docker Community Edition repository
  become: true
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - {{ ansible_architecture }}
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Set docker package name
  ansible.builtin.set_fact:
    docker_engine_package: docker-ce
  when: docker_engine_package == "DEFAULT"

- name: Define additional packages for Rocky
  ansible.builtin.set_fact:
    docker_engine_extra_packages:
      - docker-ce-cli
      - docker-compose-plugin
      - docker-buildx-plugin
  when: docker_engine_extra_packages is not truthy

