---
# Install the docker package for this system

- name: Package manager detection status
  ansible.builtin.assert:
    that:
      - ansible_pkg_mgr is in ['apt', 'yum', 'dnf', 'dnf5']
    fail_msg: "No supported package manager found!"
    success_msg: "Package manager found: {{ ansible_pkg_mgr }}"

- name: Discover existing installs
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/get-existing.yml"

- name: Prepare for package install
  block:
    - name: Run os specific install tasks
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/distros/{{ ansible_distribution | lower }}.yml"
      ignore_errors: true

    - name: Docker package name is known
      ansible.builtin.assert:
        that:
          - docker_engine_package is truthy
        fail_msg: "Docker package name is not known! Config may need to be added to docker_engine role for this OS"
        success_msg: "Docker package name is known: {{ docker_engine_package }}"

- name: Manage docker packages and dependencies
  vars:
    __docker_engine_nftables_shim_name: "{{ __docker_engine_compat_nftables_shim_package_names[ansible_distribution | lower]
        | default(__docker_engine_compat_nftables_shim_package_names.default) }}"
    __docker_engine_extra_packages: >-
      {{
        docker_engine_extra_packages + [__docker_engine_nftables_shim_name]
        if docker_engine_use_nftables_shim and docker_engine_package_state != 'absent'
        else docker_engine_extra_packages
      }}
  block:
    - name: Manage Docker package for apt-based systems
      when: ansible_pkg_mgr == 'apt'
      block:
        - name: Process version status
          ansible.builtin.include_tasks: "{{ role_path }}/tasks/versioning-apt.yml"

        - name: Manage Docker package
          when: (__docker_engine_doinstall) or docker_engine_package_state == 'absent'
          become: true
          vars:
            __docker_engine_install_package_name: >-
              {{
                docker_engine_package if docker_engine_package_state == 'absent'
                else docker_engine_package + '=' + __docker_engine_target_package_version
              }}
            # We always use 'present' for existing packages, as we want to let the versioning logic handle package selection
            __docker_engine_request_pkg_mgr_state: "{{ 'absent' if docker_engine_package_state == 'absent' else 'present' }}"
          block:
            - name: Manage Docker package (apt)
              ansible.builtin.apt:
                name: "{{ [__docker_engine_install_package_name] + __docker_engine_extra_packages}}"
                state: "{{ __docker_engine_request_pkg_mgr_state }}"
                allow_downgrade: "{{ docker_engine_allow_downgrade }}"
                autoremove: "{{ true if docker_engine_package_state == 'absent' else false }}"
              register: __docker_engine_apt_result
              notify: Restart Docker

            # This is a hack to force the package to be installed if the module decides not to
            - name: Force install docker package
              when: (__docker_engine_doinstall) and __docker_engine_apt_result is not changed
              become: true
              ansible.builtin.shell:
                cmd: "apt-get install -y {{ __docker_engine_install_package_name }}"
              notify: Restart Docker

            - name: Add new version hold - {{ __docker_engine_install_package_name }}
              when:
                - docker_engine_package_state != 'absent'
                - __docker_engine_doinstall
              become: true
              ansible.builtin.dpkg_selections:
                name: "{{ docker_engine_package }}"
                selection: hold

    - name: Manage Docker package for yum-based systems
      when: ansible_pkg_mgr == 'yum'
      block:
        - name: Process version status
          ansible.builtin.include_tasks: "{{ role_path }}/tasks/versioning-yum.yml"

        - name: Manage Docker package
          when: (__docker_engine_doinstall) or docker_engine_package_state == 'absent'
          become: true
          vars:
            __docker_engine_install_package_name: >-
              {{
                docker_engine_package if docker_engine_package_state == 'absent'
                else docker_engine_package + '-' + __docker_engine_target_package_version
              }}
            # We always use 'present' for existing packages, as we want to let the versioning logic handle package selection
            __docker_engine_request_pkg_mgr_state: "{{ 'absent' if docker_engine_package_state == 'absent' else 'present' }}"
          block:
            - name: Manage Docker package (yum)
              ansible.builtin.yum:
                name: "{{ [__docker_engine_install_package_name] + __docker_engine_extra_packages}}"
                state: "{{ __docker_engine_request_pkg_mgr_state }}"
                allow_downgrade: "{{ docker_engine_allow_downgrade }}"
                autoremove: "{{ true if docker_engine_package_state == 'absent' else false }}"
                exclude: "{{ __docker_engine_remove_package_excludes if docker_engine_package_state == 'absent' else [] }}"
              register: __docker_engine_yum_result
              notify: Restart Docker

            # This is a hack to force the package to be installed if the module decides not to
            - name: Force install docker package
              when: (__docker_engine_doinstall) and __docker_engine_yum_result is not changed
              become: true
              ansible.builtin.shell:
                cmd: "yum install -y {{ __docker_engine_install_package_name }}"
              notify: Restart Docker

    - name: Install Docker for dnf-based systems
      when: ansible_pkg_mgr in ['dnf', 'dnf5']
      block:
        - name: Process version status
          ansible.builtin.include_tasks: "{{ role_path }}/tasks/versioning-dnf.yml"

        - name: Show target package name
          ansible.builtin.debug:
            var: docker_engine_package + '-' + __docker_engine_target_package_version
            verbosity: 1

        - name: Manage Docker package
          when: (__docker_engine_doinstall) or docker_engine_package_state == 'absent'
          become: true
          vars:
            __docker_engine_install_package_name: >-
              {{
                docker_engine_package if docker_engine_package_state == 'absent'
                else docker_engine_package + '-' + __docker_engine_target_package_version
              }}
            # We always use 'present' for existing packages, as we want to let the versioning logic handle package selection
            __docker_engine_request_pkg_mgr_state: "{{ 'absent' if docker_engine_package_state == 'absent' else 'present' }}"
          block:
            - name: Manage Docker package (dnf)
              ansible.builtin.dnf:
                name: "{{ [__docker_engine_install_package_name] + __docker_engine_extra_packages}}"
                state: "{{ __docker_engine_request_pkg_mgr_state }}"
                allow_downgrade: "{{ docker_engine_allow_downgrade }}"
                autoremove: "{{ true if docker_engine_package_state == 'absent' else false }}"
                exclude: "{{ __docker_engine_remove_package_excludes if docker_engine_package_state == 'absent' else [] }}"
              register: __docker_engine_dnf_result
              notify: Restart Docker

            # This is a hack to force the package to be installed if the module decides not to
            - name: Force install docker package
              when: (__docker_engine_doinstall) and __docker_engine_dnf_result is not changed
              become: true
              ansible.builtin.shell:
                cmd: "dnf install -y {{ __docker_engine_install_package_name }}"
              notify: Restart Docker

    - name: Get current iptables alternative
      ansible.builtin.command: update-alternatives --display iptables
      register: __docker_engine_iptables_alternatives
      changed_when: false
      failed_when: false

    - name: Utilize nftables shim package for system iptables compatibility
      when:
        - docker_engine_use_nftables_shim
        - docker_engine_package_state != 'absent'
        - ('/usr/sbin/' ~ __docker_engine_nftables_shim_name) not in __docker_engine_iptables_alternatives.stdout
      become: true
      community.general.alternatives:
        name: iptables
        link: "{{ docker_engine_iptables_path }}"
        path: /usr/sbin/{{ __docker_engine_nftables_shim_name }}
        state: selected

