---
# Handle Docker version for apt-based systems

- name: Load installed package version
  when: __docker_engine_installed_version is truthy
  ansible.builtin.command:
    cmd: dpkg-query --showformat='${Version}' --show docker-ce
  changed_when: false
  register: __docker_engine_installed_pkg_raw

- name: Update APT cache
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: docker_engine_package_state == 'latest'

- name: Find matching package names
  ansible.builtin.command:
    cmd: "apt-cache madison docker-ce"
  register: __docker_engine_package_list_raw
  changed_when: false

- name: Extract applicable package versions
  ansible.builtin.set_fact:
    __docker_engine_package_versions: >-
      {{
        __docker_engine_package_list_raw.stdout_lines
        | map('regex_search', '(\s*' ~ docker_engine_package ~ '.*\|\s)(.*' ~ docker_engine_package_version ~ '\S*)(.*)', '\2')
        | flatten
        | community.general.version_sort
      }}

- name: Calculate versioning
  vars:
    __docker_engine_installed_pkg_version: >-
      {{
        __docker_engine_installed_pkg_raw.stdout | trim
        if __docker_engine_installed_version is truthy
        else
        None
      }}
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/decide-future.yml"

- name: Manage apt version hold
  vars:
    __docker_engine_hold_package_name: "{{ __docker_engine_compat_package_name }}"
  block:
    - name: Load current version hold
      ansible.builtin.command:
        cmd: "apt-mark showhold"
      register: __docker_engine_hold_list_raw
      changed_when: false

    - name: Do the version holding
      vars:
        __docker_engine_hold_list: "{{ __docker_engine_hold_list_raw.stdout_lines }}"
        __docker_engine_update_hold: "{{ 'docker-ce' not in __docker_engine_hold_list }}"
      block:
        - name: Remove existing version hold for {{ __docker_engine_hold_package_name }}
          when: >-
            __docker_engine_hold_package_name in __docker_engine_hold_list and (
              __docker_engine_update_hold or
              docker_engine_package_state == "absent"
            )
          become: true
          ansible.builtin.dpkg_selections:
            name: "{{ __docker_engine_hold_package_name }}"
            selection: install

        - name: Add new version hold - {{ __docker_engine_hold_package_name }}
          when:
            - docker_engine_package_state != 'absent'
            - __docker_engine_update_hold
            - __docker_engine_installed_version is truthy
          become: true
          ansible.builtin.dpkg_selections:
            name: "{{ __docker_engine_hold_package_name }}"
            selection: hold
