---
# Verify that the role being tested has done what it's supposed to

- name: Prepare for verification
  hosts: molecule
  tasks:
    - name: Load OS compatibility settings
      ansible.builtin.include_tasks: tasks/os_compat.yml

    - name: Load role internal configuration
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../../vars/main.yml"

    - name: Load role default configuration
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../../defaults/main.yml"
        name: __ci_role_defaults

- name: Verify system state
  hosts: molecule
  vars:
    ansible_user: molecule_runner
    __ci_docker_compat_package_name: "{{ __ci_role_defaults.docker_engine_package }}"
  tasks:
    - name: Load system facts
      ansible.builtin.setup:
        gather_subset:
          - distribution
          - pkg_mgr
          - system

    - name: Validate docker service state
      block:
        # Privileged execution is required on some systems (Fedora 41+) to access the service facts
        - name: Load system services
          become: true
          ansible.builtin.service_facts:

        - name: Verify that docker service is running
          ansible.builtin.assert:
            that:
              - ansible_facts.services['docker.service'].state | default('absent') == 'running'
            fail_msg: "Docker service is not running"
            success_msg: "Docker service is running"

    # User won't be able to run docker without sudo if the session hasn't been reset since the user was added to the 'docker' group
    - name: Force connection reset
      meta: reset_connection

    - name: Check that we can run docker without sudo
      ansible.builtin.command:
        cmd: "docker ps"
      become: true
      become_user: "{{ ansible_user }}"
      changed_when: false

    - name: Run a test container
      community.docker.docker_container:
        name: test_container
        image: hello-world
        state: started
        auto_remove: true

    - name: Validate version lock
      block:
        - name: Load current version lock
          when: ansible_os_family | lower == 'redhat'
          ansible.builtin.command:
            cmd: "yum versionlock list"
          register: __ci_versionlock_list_raw
          changed_when: false

        - name: Load current version lock
          when: ansible_os_family | lower == 'debian'
          ansible.builtin.fail:
            msg: "Apt is not yet supported for this role! Add APT support and receive a 🍪!"

        - name: Extract version lock information
          when: __ci_versionlock_list_raw.stdout is truthy
          block:
            - name: Parse version lock list (dnf)
              when: ansible_pkg_mgr == 'dnf'
              ansible.builtin.set_fact:
                __ci_versionlock_list: >-
                  {{ __ci_versionlock_list_raw.stdout_lines | map('regex_search', '(.*)\.\*', '\1') | reject('none') | list }}

            - name: Parse version lock list (dnf5)
              when: ansible_pkg_mgr == 'dnf5'
              ansible.builtin.set_fact:
                __ci_versionlock_list: >-
                  {{ __ci_versionlock_list_raw.stdout | regex_findall('Package name: ' + __ci_docker_compat_package_name + '\n.*?evr = (.+?)$', multiline=True) |
                  map('regex_replace', '\d+:', __ci_docker_compat_package_name + '-' ) | list }}

        - name: Docker package is version locked
          ansible.builtin.assert:
            that:
              - __ci_versionlock_list | select('search', 'docker') is truthy
            fail_msg: "Docker package is not version locked"
            success_msg: "Docker package is version locked"

        # Validate string parsing with multiple version locks
        #  - next execution of role below should fail idempotence if version lock is not respected
        - name: Add additional version locks
          become: true
          block:
            - name: Add additional version lock (dnf)
              when: ansible_pkg_mgr in ['dnf', 'dnf5']
              community.general.dnf_versionlock:
                state: present
                name: bash

            - name: Add additional version lock (yum)
              when: ansible_pkg_mgr == 'yum'
              community.general.yum_versionlock:
                name: bash
                state: present

- name: Verify Docker Downgrade
  hosts: molecule
  vars:
    ci_target_version: "{{ ci_docker_low_version }}"
    ansible_user: molecule_runner
  tasks:
     - name: Downgrading docker to version
       ansible.builtin.debug:
         var: ci_target_version

     - name: Install 2nd to latest version of docker, and give ci user docker permissions
       ansible.builtin.include_role:
         name: docker_engine
       vars:
         docker_engine_package_version: "{{ ci_target_version }}"
         docker_engine_users:
           - "{{ ansible_user }}"
         docker_engine_allow_downgrade: true

     - name: Get the docker engine version
       ansible.builtin.command:
         cmd: "docker system info --format '{% raw %}{{ json .ServerVersion }}{% endraw %}'"
       register: __ci_docker_version_raw
       changed_when: false

     - name: Docker downgrade was successful
       ansible.builtin.assert:
         that:
           - ci_target_version in __ci_docker_version_raw.stdout | from_json
         fail_msg: "The expected docker version ({{ ci_target_version }}) is not installed"
         success_msg: "The expected docker version ({{ __ci_docker_version_raw.stdout | from_json }}) is installed"

- name: Validate state management
  hosts: molecule
  vars:
    ci_target_version: "{{ ci_docker_low_version }}"
    ansible_user: molecule_runner
  tasks:
    # Docker version is assumed to be < target version for these checks
    - name: Get docker service original start time
      become: true
      ansible.builtin.command:
        cmd: "systemctl show -p ActiveEnterTimestamp docker"
      changed_when: false
      register: __ci_docker_service_original_start_timestamp_raw

    - name: Run docker role with no-restart flag
      ansible.builtin.include_role:
        name: docker_engine
      vars:
        docker_engine_package_version: "{{ ci_docker_low_version }}"
        docker_engine_package_state: present
        docker_engine_allow_restart: false
        # Include config change to make sure no-restart is respected
        docker_engine_daemon_options:
          log-driver: "json-file"
          log-opts:
            max-size: "40m"
            max-file: "4"

    - name: Get docker service current start time
      become: true
      ansible.builtin.command:
        cmd: "systemctl show -p ActiveEnterTimestamp docker"
      changed_when: false
      register: __ci_docker_service_current_start_timestamp_raw

    - name: Verify service uptime
      ansible.builtin.assert:
        that:
          - __ci_docker_service_original_start_timestamp_raw.stdout == __ci_docker_service_current_start_timestamp_raw.stdout
        fail_msg: "Service was restarted"
        success_msg: "Service was not restarted"

    - name: Try not-allowed update
      block:
        - name: Run docker role with newer version and no-restart flag (should fail)
          ansible.builtin.include_role:
            name: docker_engine
          vars:
            docker_engine_package_version:  "{{ ci_target_version }}"
            docker_engine_package_state: latest
            docker_engine_allow_restart: false
      rescue:
        - name: Validate failure state
          ansible.builtin.assert:
            that:
              - "ansible_failed_result | failed"
              - ansible_failed_result.msg | regex_search('Version mask .* is not satisfied by installed version .*')
            fail_msg: "Role allowed a non-allowed update"
            success_msg: "Role did not allow a non-allowed update"

    - name: Get docker service current start time
      become: true
      ansible.builtin.command:
        cmd: "systemctl show -p ActiveEnterTimestamp docker"
      changed_when: false
      register: __ci_docker_service_current_start_timestamp_raw

    - name: Verify service uptime
      ansible.builtin.assert:
        that:
          - __ci_docker_service_original_start_timestamp_raw.stdout == __ci_docker_service_current_start_timestamp_raw.stdout
        fail_msg: "Service was restarted"
        success_msg: "Service was not restarted"

- name: Verify Docker Upgrade
  hosts: molecule
  vars:
    ci_target_version: "{{ ci_docker_high_version }}"
    ansible_user: molecule_runner
    __ci_docker_compat_package_name: "{{ __ci_role_defaults.docker_engine_package }}"
  tasks:
    - name: Verify 'latest' upgrade logic
      block:
        - name: Load current docker version
          ansible.builtin.command:
            cmd: "docker system info --format '{% raw %}{{ json .ServerVersion }}{% endraw %}'"
          register: __ci_docker_start_version_raw
          changed_when: false

        - name: Load current installed docker package
          block:
            - name: Load installed docker package (starting)
              when: ansible_os_family | lower == 'redhat'
              ansible.builtin.command:
                cmd: rpm -q {{ __ci_docker_compat_package_name }}
              register: __ci_docker_start_rpm_package_installed_raw
              changed_when: false

            - name: Load current installed docker package
              when: ansible_os_family | lower == 'debian'
              ansible.builtin.fail:
                msg: "Apt is not yet supported for this role! Add APT support and receive a 🍪!"

        - name: Run docker role with latest flag (should upgrade)
          ansible.builtin.include_role:
            name: docker_engine
          vars:
            docker_engine_package_version:  "{{ ci_target_version }}"
            docker_engine_package_state: latest
            docker_engine_allow_restart: true
            docker_engine_users:
              - "{{ ansible_user }}"

        - name: Get the docker engine version
          ansible.builtin.command:
            cmd: "docker system info --format '{% raw %}{{ json .ServerVersion }}{% endraw %}'"
          register: __ci_docker_version_raw
          changed_when: false

        - name: Verify upgrade status
          vars:
            __ci_docker_version_decreased: "{{ __ci_docker_start_version_raw.stdout is version_compare(__ci_docker_version_raw.stdout, '<') }}"
            __ci_docker_version_equal: "{{ __ci_docker_start_version_raw.stdout is version_compare(__ci_docker_version_raw.stdout, '==') }}"
          block:
            - name: Load current installed docker package
              when: ansible_os_family | lower == 'redhat'
              ansible.builtin.command:
                cmd: rpm -q {{ __ci_docker_compat_package_name }}
              register: __ci_docker_rpm_package_installed_raw
              changed_when: false

            - name: Load current installed docker package
              when: ansible_os_family | lower == 'debian'
              ansible.builtin.fail:
                msg: "Apt is not yet supported for this role! Add APT support and receive a 🍪!"

            - name: Verify package status
              ansible.builtin.assert:
                that:
                  - __ci_docker_rpm_package_installed_raw.stdout | trim != __ci_docker_start_rpm_package_installed_raw.stdout | trim
                  - ci_target_version in __ci_docker_version_raw.stdout | from_json
                fail_msg: >
                  The expected docker version change ({{ __ci_docker_start_version_raw.stdout | trim }} --> {{ ci_target_version }}) did not occurr!
                  Original version: {{ __ci_docker_start_version_raw.stdout | trim }}
                  Current version: {{ __ci_docker_version_raw.stdout | from_json }}
                success_msg: "The expected docker version ({{ __ci_docker_version_raw.stdout | from_json }}) is installed"

    - name: Install new major release version of docker
      ansible.builtin.include_role:
        name: docker_engine
      vars:
        docker_engine_package_version:  "{{ ci_target_version }}"
        docker_engine_allow_restart: true
        docker_engine_users:
          - "{{ ansible_user }}"

    - name: Get the docker engine version
      ansible.builtin.command:
        cmd: "docker system info --format '{% raw %}{{ json .ServerVersion }}{% endraw %}'"
      register: __ci_docker_version_raw
      changed_when: false

    - name: Validate upgrade status
      ansible.builtin.assert:
        that:
          - ci_target_version in __ci_docker_version_raw.stdout | from_json
        fail_msg: "The expected docker version ({{ ci_target_version }}) is not installed"
        success_msg: "The expected docker version ({{ __ci_docker_version_raw.stdout | from_json }}) is installed"

- name: Verify Docker Removal
  hosts: molecule
  vars:
    ansible_user: molecule_runner
  tasks:
    - name: Remove docker
      ansible.builtin.include_role:
        name: docker_engine
      vars:
        docker_engine_package_state: absent

    - name: Check that we can't run docker
      become: true
      ansible.builtin.command:
        cmd: "docker --version"
      register: __ci_docker_version_raw
      failed_when: false

    - name: 🪱 Show docker command output
      ansible.builtin.debug:
        var: __ci_docker_version_raw
        verbosity: 1

    - name: Docker is not installed
      ansible.builtin.assert:
        that:
          - "'No such file or directory' in __ci_docker_version_raw.msg"
        fail_msg: "Docker is still installed"
        success_msg: "Docker is not installed"

