---
# handlers file for Docker

- name: Restart Docker
  when:
    - docker_engine_service_manage | bool
    - docker_engine_allow_restart | bool
    - docker_engine_package_state != 'absent'
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/handlers/restart-docker.yml"
