---
# handlers file for Docker

- name: Restart Docker
  when:
    - docker_engine_service_manage | bool
    - docker_engine_allow_restart | bool
    - docker_engine_package_state != 'absent'
  become: true
  ansible.builtin.service:
    name: docker
    state: "{{ docker_engine_restart_handler_state }}"
