---
role_name_check: 0
dependency:
  name: galaxy
driver:
  name: default
  options:
    managed: true
platforms:
  - name: role-docker_engine-ec2-al2
    type: ec2
    image: ami-028bd07c62e764718
    region: us-west-2
    instance_type: t3.micro
    ssh_user: molecule_runner
    vpc_id: vpc-07bd460b98a3fb162
    vpc_subnet_id: subnet-018b2c7fdd47921c2
    boot_wait_seconds: 10
    hostvars:
      ci_docker_low_version: "20.10"
      ci_docker_high_version: "25.0"
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../resources/create.yml
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
    side_effect: ../resources/side_effect.yml
    verify: ../resources/verify.yml
    cleanup: ../resources/cleanup.yml
    destroy: ../resources/destroy.yml
  config_options:
    defaults:
      gathering: explicit
      playbook_vars_root: top
      verbosity: ${ANSIBLE_VERBOSITY:-0}
  env:
    ARA_API_CLIENT: ${ARA_API_CLIENT:-'http'}
    ARA_API_SERVER: ${ARA_API_SERVER:-'http://localhost:8000'}
    ARA_DEFAULT_LABELS: ${ARA_DEFAULT_LABELS:-'testing,molecule'}
    # To use Ara with molecule:
    #  export the ANSIBLE_CALLBACK_PLUGINS env var with the output of 'python3 -m ara.setup.callback_plugins'
    ANSIBLE_CALLBACK_PLUGINS: ${ANSIBLE_CALLBACK_PLUGINS}
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
  enabled: true

