---
# OS compatibility tasks

### NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE ###
#                                                                    #
#   Update this file with any OS environment compatibility tasks!    #
#                                                                    #
### NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE ###

- name: Load host facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
    filter:
      - ansible_distribution*

- name: Set legacy OS vars
  when: >
    ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" or
    ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
  ansible.builtin.set_fact:
    ansible_python_interpreter: /usr/local/bin/python3.10

